ARG COMPOSE_AMAZEEIO_VERSION=latest
FROM uselagoon/solr-8-drupal:${COMPOSE_AMAZEEIO_VERSION}

# Overwrite/extend existing config with everything provided.
COPY ./solr-conf/* /solr-conf/conf/

RUN rm -rf /opt/solr/server/solr/mycores/drupal && precreate-core drupal /solr-conf

CMD ["solr-foreground"]
