ARG COMPOSE_AMAZEEIO_VERSION=latest
FROM amazeeio/varnish-drupal:$COMPOSE_AMAZEEIO_VERSION

# Note: We use this custom Dockerfile only such that the variable $COMPOSE_AMAZEEIO_VERSION can be applied.
# Applying variables inside of docker-compose does not work with amazeeio's lagoon infrastructure.
