ARG COMPOSE_AMAZEEIO_VERSION
FROM amazeeio/solr:6.6-drupal-${COMPOSE_AMAZEEIO_VERSION}

# Overwrite/extend existing config with everything provided.
COPY ./solr-conf/* /solr-conf/conf/

RUN rm -rf /opt/solr/server/solr/mycores/drupal && precreate-core drupal /solr-conf

CMD ["solr-foreground"]
