ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM amazeeio/nginx-drupal

COPY --from=cli /app /app

# Define where the Drupal Root is located
ENV WEBROOT=web

ADD nginx/drupal/* /etc/nginx/conf.d/drupal/
ADD nginx/helpers/* /etc/nginx/helpers/

COPY nginx/*.conf /etc/nginx/conf.d/

RUN fix-permissions /etc/nginx