ARG COMPOSE_AMAZEEIO_VERSION=latest
FROM amazeeio/redis:$COMPOSE_AMAZEEIO_VERSION

# Note: We use this custom Dockerfile only such that the variable $COMPOSE_AMAZEEIO_VERSION can be applied.
# Applying variables inside of docker-compose does not work with amazeeio's lagoon infrastructure.


# LDP-614: Ensure only volatile items (cache items) are affected from LRU eviction.
RUN sed -i '/maxmemory-policy allkeys-lru/c\maxmemory-policy volatile-lru' /etc/redis/redis.conf
