ARG CLI_IMAGE
ARG COMPOSE_AMAZEEIO_VERSION=latest
FROM ${CLI_IMAGE} as cli
FROM amazeeio/nginx-drupal:${COMPOSE_AMAZEEIO_VERSION}

COPY --from=cli /app /app

# Define where the Drupal Root is located
ENV WEBROOT=web

ADD nginx/drupal/* /etc/nginx/conf.d/drupal/
ADD nginx/helpers/* /etc/nginx/helpers/

COPY nginx/*.conf /etc/nginx/conf.d/

RUN fix-permissions /etc/nginx