# Extends the main docker-compose file depending on the active environment.

# This mostly applies low-memory settings.
version: '2.3'
services:
  varnish:
    environment:
      CACHE_SIZE: 16M
  redis:
    environment:
      MAXMEMORY: 32m
  solr:
    environment:
      SOLR_JAVA_MEM: -Xms64M -Xmx128M
  mariadb:
    environment:
      MARIADB_INNODB_LOG_FILE_SIZE: 32M
      MARIADB_INNODB_BUFFER_POOL_SIZE: 4M
      MARIADB_INNODB_BUFFER_POOL_INSTANCES: 1
      MARIADB_LOG_SLOW: 1
      # MARIADB_LOG_QUERIES: 1
