version: "3.5"
services:
  web:
    hostname: $COMPOSE_PROJECT_NAME
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - WEB_IMAGE
        - WEB_IMAGE_VERSION
        - WEB_PROVISION_VARS_PATTERN
        - WEB_PROVISION_PLAYBOOK_COMMAND=${WEB_PROVISION_PLAYBOOK_COMMAND:-ansible-playbook lamp.yml --tags tools --skip-tags=apache -vv}
        - WEB_EXTRA_PLAYBOOK_PATTERN
        - WEB_EXTRA_PLAYBOOK_COMMAND=${WEB_EXTRA_PLAYBOOK_COMMAND:-ansible-playbook extra-play*.yml --skip-tags=php -vv}
        - WEB_DIRECTORY
    image: ${COMPOSE_PROJECT_NAME}_web
    ports:
     - "$WEB_LISTEN_IP:$WEB_HTTP_PORT:80"
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: $COMPOSE_CODE_DIR
        target: /srv/default/vcs
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.local

volumes:
  mysql_data:
