# Extends the main docker-compose file depending on the active environment.
# The file is automatically picked up thanks to .env for localdev setting COMPOSE_FILE accordingly.
version: '2.3'
services:
  varnish:
    ports:
      - "${WEB_LISTEN_IP:-127.0.0.1}:${WEB_HTTP_PORT:-80}:80"
  solr:
    ports:
      # exposes the port 8983 with a random local port, find it with `docker-compose port solr 8983`
      - "127.0.0.1::8983"
  mariadb:
    # amazeeio image has problems on btrfs: https://jira.mariadb.org/browse/MDEV-16015
    # For now, we can downgrade to the galera version.
    image: amazeeio/mariadb-galera-drupal
    ports:
      # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
      - "127.0.0.1::3306"
  php:
    environment:
      XDEBUG_ENABLE: "true"
      PHP_MAX_EXECUTION_TIME: 900
      PHP_MAX_INPUT_VARS: 2000
      PHP_MAX_FILE_UPLOADS: 20
      PHP_MEMORY_LIMIT: 400M
      PHP_DISPLAY_ERRORS: 'On'
      PHP_DISPLAY_STARTUP_ERRORS: 'On'
