# Extends the main docker-compose file depending on the active environment.
# The file is automatically picked up thanks to .env for localdev setting COMPOSE_FILE accordingly.
version: '2.3'
services:
  varnish:
    ports:
      - "${WEB_LISTEN_IP:-127.0.0.1}:${WEB_HTTP_PORT:-80}:80"
    networks:
      traefik:
        # Make this container available under the main hostname for other containers, so the cli
        # container can use it to access the site during test runs. This works even during localdev
        # when the hostname would resolve to 127.0.0.1.
        aliases:
          - ${COMPOSE_HOSTNAME}
  solr:
    ports:
      # exposes the port 8983 with a random local port, find it with `docker-compose port solr 8983`
      - "127.0.0.1::8983"
  mariadb:
    # amazeeio image has problems on btrfs: https://jira.mariadb.org/browse/MDEV-16015
    # For now, we can downgrade to the galera version.
    build:
      args:
        COMPOSE_MARIADB_IMAGE: "mariadb-galera-drupal"
    ports:
      # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
      - "127.0.0.1::3306"
  php:
    environment:
      # Also see docker-compose.development.yml for other config options.
      XDEBUG_ENABLE: "true"
