# Extends the main docker-compose file depending on the active environment.

# This mostly applies low-memory settings.
version: '2.3'
services:
  varnish:
    environment:
      CACHE_SIZE: 16M
  redis:
    environment:
      MAXMEMORY: 32m
  solr:
    environment:
      SOLR_JAVA_MEM: -Xms64M -Xmx128M
  mariadb:
    environment:
      MARIADB_INNODB_LOG_FILE_SIZE: 32M
      MARIADB_INNODB_BUFFER_POOL_SIZE: 4M
      MARIADB_INNODB_BUFFER_POOL_INSTANCES: 1
      MARIADB_LOG_SLOW: 1
      # MARIADB_LOG_QUERIES: 1
  php:
    environment:
      # XDEBUG_ENABLE: "true"
      PHP_MAX_EXECUTION_TIME: 900
      PHP_MAX_INPUT_VARS: 2000
      PHP_MAX_FILE_UPLOADS: 20
      PHP_MEMORY_LIMIT: 400M
      PHP_DISPLAY_ERRORS: 'On'
      PHP_DISPLAY_STARTUP_ERRORS: 'On'
